[admin] sign in and sign out as administrator and administrators crud
oiax/live_reverse_proxy pull request #19
Opened 2024-09-04 07:03 UTC by ShinyaSakamoto

close #12 
close #14

2024-09-05 05:30 UTC, kuroda requested changes
`mix compile` produces these warnings:

```
    warning: variable "f" is unused (if the variable is not meant to be used, prefix it with an underscore)
    │
  8 │       :let={f}
    │       ~~~~~~~~
    │
    └─ lib/live_web_server_web/controllers/session_html/new.html.heex:8: LiveWebServerWeb.SessionHTML.new/1

    warning: attribute "type" in component LiveWebServerWeb.CoreComponents.input/1 must be one of ["checkbox", "color", "date", "datetime-local", "email", "file", "month", "number", "password", "range", "search", "select", "tel", "text", "textarea", "time", "url", "week"], got: :password
    │
  6 │     <.input field={f[:password]} class="input" label="Password" type={:password} />
    │     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └─ lib/live_web_server_web/live/admin_live/new_administrator.html.heex:6: (file)
```

2024-09-05 07:28 UTC, ShinyaSakamoto commented
@kuroda This has been fixed. Please check.

2024-09-05 23:27 UTC, kuroda requested changes
I found the following problems:

1. When I submit a new administrator registration form without entering a password, no error message is displayed. 
2. After successfully registering an administrator in the new administrator registration form, the form does not disappear.

Please fix them.

2024-09-06 02:49 UTC, kuroda approved these changes

2024-09-06 02:49 UTC, merged