[admin] Implement the redirection functionality
oiax/live_reverse_proxy pull request #24
Opened 2024-09-09 08:23 UTC by ShinyaSakamoto

close #21

2024-09-13 02:54 UTC, kuroda commented on priv/repo/seeds/dev/virtual_hosts_and_servers.exs
>  owner_name_and_hostname_pairs = [
Since the number of elements in the tuples is now 3 instead of 2, change the variable name to `virtual_host_tuples`.

2024-09-13 02:55 UTC, kuroda requested changes
Please read my comments and modify your code.

2024-09-13 07:42 UTC, ShinyaSakamoto commented
@kuroda   This has been fixed. Please check.

2024-09-15 11:31 UTC, kuroda approved these changes

2024-09-15 11:31 UTC, merged