Branching process added due to the addition of superadmin.
oiax/live_reverse_proxy pull request #25
Opened 2024-09-10 13:17 UTC by kkana6624

# Related Issues
#22 Introduce the concept of super administrator

# Changes
* Add new migration file
* AdminLive with additional processing by adding superadmin

# Question
* I assume from the Issue that the general administrator can update himself but not other administrators.
Is that Ok?

# Review Perspective
* Whether the content of the implementation is appropriate
* Whether UI behaviour is appropriate
* Whether the UI display (superadmin) is as expected
* Whether the format and title of the pull request are appropriate

![add_superadmin](https://github.com/user-attachments/assets/b88be0d2-808c-49e5-aa6d-b5f946132ab1)

Sign in with taro(superadmin)
![image](https://github.com/user-attachments/assets/cfc0f942-f04c-463b-aed1-243de6cb040c)

Sign in with jiro
![image](https://github.com/user-attachments/assets/f7fda998-de15-4fd9-bf1b-28b25aa5e71a)

2024-09-10 13:31 UTC, kuroda commented
@kkana6624 

> I assume from the Issue that the general administrator can update himself but not other administrators. Is that Ok?

No. A non-super administartor cannot update oneself.

I plan to provide a separate UI for administrators to change their own information.

2024-09-10 13:43 UTC, kuroda requested changes
Please read my comments and correct the source code.

2024-09-10 13:43 UTC, kuroda commented on lib/live_web_server_web/live/admin_live/administrator.html.heex
> +  <% end %>
Here, You'd be better off writing it like this:

```html
  <td>
    <%= @administrator.username %> 
    <%= if @administrator.superadmin %>(superadmin)<% end%>
  </td>
```

2024-09-10 13:43 UTC, kuroda commented on priv/repo/migrations/20240910011342_add_super_admin.exs
> +end
Until Version 1 of this software is released, please do not create migration scripts that perform `ALTER` operations.

Instead, rewrite your existing migration scripts _directly_.

Also, the `superadmin` column is not required for `active_administrators` and `deleted_administrators`.

2024-09-11 07:05 UTC, kkana6624 commented on lib/live_web_server_web/live/admin_live/administrator.html.heex
> +  <% end %>
I ran the code you suggested in my environment and it did not work as expected, so I modified it as follows.
```html 
  <td>
    <%= @administrator.username %>
    <%= if @administrator.superadmin, do: "(superadmin)" %>
  </td>
```

The UI seems to be working as expected, but please let us know if there are any problems.

2024-09-11 07:07 UTC, kkana6624 commented on priv/repo/migrations/20240910011342_add_super_admin.exs
> +end
Unnecessary migration files were deleted and appended to existing migration files.

Also, unnecessary edits have been removed.

2024-09-11 07:14 UTC, kkana6624 commented
@kuroda 
I have corrected the points that you pointed out. Please confirm.

2024-09-12 00:28 UTC, kuroda commented
@kkana6624 

Thank you.

The `btn-danger` class is specified for the “Delete” button in the admin table. This class is not in daisyUI. Use `btn-neutral`.

Also, although not included in the initial instructions, please address the following additional points:

* If a user is logged in as a non-super administrator, disable the "Undelete" button in the deleted administrators table.

2024-09-13 12:55 UTC, kkana6624 commented
@kuroda 
Incorrect CSS class designations have been corrected.

Additional requirements have also been implemented.

If the user is a superadmin
![image](https://github.com/user-attachments/assets/84153589-a989-4058-90cd-387c0d0cb610)

If the user is not a superadmin
![image](https://github.com/user-attachments/assets/5dfdad60-1bf3-4de8-8530-f70237dfab3d)

2024-09-13 12:59 UTC, kkana6624 commented
Although not related to this pull request, 
it was slightly disconcerting that the screen did not show who was logged in.

Is it because the users themselves know who is signed in and therefore it is unnecessary?

2024-09-15 11:03 UTC, kuroda commented
@kkana6624 

I have confirmed that all behavior is correct. Thank you very much.

Now, your PR contains two commits. I believe that a PR of this size should be submitted as a single commit.

So, please use the `git rebase -i origin/main` command to squash the commits into one.

The message of that single commit should be in the following format:

```
Introduce the concept of super administrator

* Fixed a migration file, a schema file, and a seeding script
* Disabled some buttons for non-super administrators
```

2024-09-15 11:29 UTC, kuroda commented
@kkana6624 

> it was slightly disconcerting that the screen did not show who was logged in.

You are right.

I opened a new issue #26 to address this inconvenience and add a new feature.

2024-09-15 12:28 UTC, kkana6624 commented
@kuroda 
Thank you for your review.
I have aggregate the commits and re-pushed.

2024-09-16 04:07 UTC, kuroda approved these changes

2024-09-16 04:07 UTC, merged