Fix : Sign In Page Style
oiax/live_reverse_proxy pull request #34
Opened 2024-11-21 17:20 UTC by k70suK3-k06a7ash1

- resolve #31

2024-11-21 17:24 UTC, k70suK3-k06a7ash1 commented
@kuroda 
please check this PR

THX

2024-11-23 00:46 UTC, kuroda requested changes
See my comments

2024-11-23 00:46 UTC, kuroda commented on lib/live_web_server_web/components/layouts/app.html.heex
> +
Remove the extra line breaks.

2024-11-23 00:46 UTC, kuroda commented on lib/live_web_server_web/components/layouts/app.html.heex
> +
Remove the extra line breaks.

2024-11-26 11:54 UTC, closed without merging